development:
  adapter: postgresql
  encoding: unicode
  database: setphrase_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: setphrase_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: setphrase_production
  pool: 5
  timeout: 5000
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
  host: localhost
